server:
  port: 8082

com:
  zeero:
    beer-service-host: http://localhost:8080

# artemis configuration
spring:
  application:
    name: order-service
  artemis:
    user: artemis
    password: simetraehcapa
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  # port configuration to zipkin
  zipkin:
    baseUrl: http://localhost:9411/
