server:
  port: 8082

com:
  zeero:
    beer-service-host: http://localhost:8080

# artemis configuration
spring:
  artemis:
    user: artemis
    password: simetraehcapa
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-as-timestamps-as-nanoseconds: true
