DROP DATABASE IF EXISTS `orderservice`;
DROP USER IF EXISTS `order_service`@`%`;
CREATE DATABASE IF NOT EXISTS orderservice CHARACTER SET utf8mb COLLATE utf8mb_unicode_ci;
CREATE USER IF NOT EXISTS `order_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `orderservice`.* TO `order_service`@`%`;
FLUSH PRIVILEGES;